version: '3'
services:
  app:
    build: .
    ports:
      - 8010:8010
    networks:
      - overlay
  mongodb:
    image: mongo:3
    ports:
      - 27017:27017
    networks:
      - overlay
    volumes:
      - mongo-data:/data/db
networks:
    overlay:
volumes:
    mongo-data:
